apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: employees
spec:
  selector:
    matchLabels:
      app: employees
  replicas: 3
  template:
    metadata:
      labels:
        app: employees
    spec:
      containers:
      - name: guestbook
        image: 969395510710.dkr.ecr.us-east-1.amazonaws.com/clo835-week3-harman:app.v0.1
        # image: gcr.io/google-samples/gb-frontend:v4
        env:
        - name: DBHOST
          value: "10.244.0.5"
        - name: DBPORT
          value: "3306"
        - name: DBPWD
          value: "db_pass123"  
        - name: DBUSER
          value: "root"
        ports:
        - containerPort: 8080