apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: frontend
  labels:
    app: guestbook
spec:
  # modify replicas according to your case
  replicas: 3
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
      - name: frontend
        image: 969395510710.dkr.ecr.us-east-1.amazonaws.com/clo835-week3-harman:app.v0.1
        ports:
        - containerPort: 3306
        env:
        - name: DBHOST
          value: "0.0.0.0"
        - name: DBPORT
          value: "3306"
        - name: DBPWD
          value: "db_pass123" 