apiVersion: v1
kind: Pod
metadata:
  name: backend
  labels:
spec:
  containers:
  - name: backend
    image: 969395510710.dkr.ecr.us-east-1.amazonaws.com/clo835-week3-harman:db.v0.1
    ports:
    - containerPort: 3306
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: db_pass123
    - name: DBPORT
      value: "3306"