apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  replicas: 3
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: backend
        image: 969395510710.dkr.ecr.us-east-1.amazonaws.com/clo835-week3-harman:database.01
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: db_pass123
        - name: DBHOST
          value: mysqldb